/* Generated by Yosys 0.55+109 (git sha1 b25259aa9, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "alu.v:1.1-21.10" *)
module alu(a, b, sel, out, carry);
  (* src = "alu.v:9.1-19.4" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  (* src = "alu.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "alu.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "alu.v:6.16-6.21" *)
  output carry;
  reg carry;
  (* src = "alu.v:5.22-5.25" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "alu.v:4.17-4.20" *)
  input [2:0] sel;
  wire [2:0] sel;
  sky130_fd_sc_hd__clkinv_1 _048_ (
    .A(a[1]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _049_ (
    .A(b[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _050_ (
    .A(sel[2]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _051_ (
    .A(a[3]),
    .SLEEP(b[3]),
    .X(_005_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _052_ (
    .A(sel[2]),
    .SLEEP(sel[1]),
    .X(_001_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _053_ (
    .A(sel[0]),
    .SLEEP(_001_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _054_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xor2_1 _055_ (
    .A(b[3]),
    .B(a[3]),
    .X(_008_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _056_ (
    .A(a[2]),
    .SLEEP(b[2]),
    .X(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _057_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _058_ (
    .A(b[2]),
    .B(a[2]),
    .X(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _059_ (
    .A(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _060_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _061_ (
    .A1(_003_),
    .A2(a[0]),
    .B1(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _062_ (
    .A1(b[1]),
    .A2(_002_),
    .B1(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _063_ (
    .A1(_012_),
    .A2(_015_),
    .B1(_009_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o21ai_0 _064_ (
    .A1(_008_),
    .A2(_016_),
    .B1(_006_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _065_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _066_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21ai_0 _067_ (
    .A1(_013_),
    .A2(_018_),
    .B1(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__maj3_1 _068_ (
    .A(b[2]),
    .B(a[2]),
    .C(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _069_ (
    .A1(b[3]),
    .A2(a[3]),
    .B1(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o32ai_1 _070_ (
    .A1(_006_),
    .A2(_007_),
    .A3(_022_),
    .B1(_017_),
    .B2(_005_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _072_ (
    .A(_004_),
    .B(sel[1]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _073_ (
    .A(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _074_ (
    .A1(_004_),
    .A2(sel[0]),
    .B1(sel[1]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a22oi_1 _075_ (
    .A1(sel[0]),
    .A2(_025_),
    .B1(_026_),
    .B2(_018_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o32ai_1 _076_ (
    .A1(sel[0]),
    .A2(_018_),
    .A3(_024_),
    .B1(_027_),
    .B2(_023_),
    .Y(out[0])
  );
  sky130_fd_sc_hd__or3_1 _077_ (
    .A(_003_),
    .B(a[0]),
    .C(_013_),
    .X(_028_)
  );
  sky130_fd_sc_hd__or3_1 _078_ (
    .A(_004_),
    .B(sel[1]),
    .C(sel[0]),
    .X(_029_)
  );
  sky130_fd_sc_hd__nand3b_1 _079_ (
    .A_N(_006_),
    .B(_026_),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _080_ (
    .A(_013_),
    .B(_018_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _081_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(sel[0]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _082_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o32ai_1 _083_ (
    .A1(_024_),
    .A2(_032_),
    .A3(_033_),
    .B1(_029_),
    .B2(_013_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a31oi_1 _084_ (
    .A1(_006_),
    .A2(_014_),
    .A3(_028_),
    .B1(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21ai_0 _085_ (
    .A1(_030_),
    .A2(_031_),
    .B1(_035_),
    .Y(out[1])
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(_011_),
    .B(_015_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(_011_),
    .B(_020_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _088_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(sel[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o32ai_1 _089_ (
    .A1(_010_),
    .A2(_024_),
    .A3(_038_),
    .B1(_029_),
    .B2(_012_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a21oi_1 _090_ (
    .A1(_006_),
    .A2(_036_),
    .B1(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _091_ (
    .A1(_030_),
    .A2(_037_),
    .B1(_040_),
    .Y(out[2])
  );
  sky130_fd_sc_hd__and2_0 _092_ (
    .A(_008_),
    .B(_016_),
    .X(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _093_ (
    .A1(_021_),
    .A2(_030_),
    .B1(_029_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_008_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _095_ (
    .A1(b[3]),
    .A2(a[3]),
    .B1(sel[0]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _096_ (
    .A(_007_),
    .B(_024_),
    .C(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(_008_),
    .B(_030_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a21oi_1 _098_ (
    .A1(_021_),
    .A2(_046_),
    .B1(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o211ai_1 _099_ (
    .A1(_017_),
    .A2(_041_),
    .B1(_043_),
    .C1(_047_),
    .Y(out[3])
  );
  (* src = "alu.v:9.1-19.4" *)
  always @*
    if (!_001_) carry = _000_;
endmodule
